config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    devise_parameter_sanitizer.permit(:up_date,keys:[:name,:introduction])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = BookComment.new(book_comment_params)
    @comment.user_id = current_user.id
    @comment.book_id = @book.id
    @comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = BookComment.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
      params.require(:book_comment).permit(:comment)
  end


  def correct_user
    @comment = BookComment.find(params[:id])

    if current_user.id != @comment.user.id
      redirect_to books_path
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :correct_user, only: [:edit, :update]


  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book_comment = BookComment.new
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    book = Book.find(params[:id])
    # refactering because book model has belong_to
    if current_user.id != book.user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :correct_user, only: [:edit, :update]
    
  def index
    @users = User.all
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(params[:id])
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/_book.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book, url: '/books', method: :post do |f| %>
  <div class="form-group">
    <h4>Title</h4>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <h4>Opinion</h4>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div>
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book.id), class: "text-danger", method: :delete do %>
    <i class="fa fa-heart"></i>
    <%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book.id), method: :post do %>
    <i class="fa fa-heart"></i>
    <%= book.favorites.count %>
  <% end %>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto'>
      <h1>Editing Book</h1>
      <%= render 'error', model: @book %>
      <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </div>

        <div class="form-group">
          <%= f.label :Opinion %><br>
          <%= f.text_area :body %>
        </div>

        <div class="form-group">
          <%= f.submit 'Update Book',class: 'btn btn-success' %>
        </div>
      <% end %>

      <%= link_to "Show", book_path %>
       |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'error', model: @book %>
      <%= render 'users/user', user: @user %>
      <%= render 'book', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <% if book.user.profile_image.attached? %>
                    <%= image_tag book.user.profile_image, size: "40x40" %>
                  <% else %>
                    <%= image_tag 'no_image', size: "40x40" %>
                  <% end %>
    	          <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <%= render 'favorite', book: book %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/user', user: @user %>
      <%= render 'book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@books.user.id) do %>
              <% if @books.user.profile_image.attached? %>
                <%= image_tag @books.user.profile_image, size: "40x40" %>
              <% else %>
                <%= image_tag 'no_image', size: "40x40" %>
              <% end %>
            <% end %>
            <br>
            <%= link_to @books.user.name, user_path(@books.user.id) %>
          </td>
          <td><%= link_to @books.title, book_path(@books.id) %></td>
          <td><%= @books.body %></td>
          <% if @books.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path, class: 'btn btn-sm btn-success' %></td>
            <td><%= link_to "Destroy", book_path(@books.id), method: :delete, "data-confirm"  => "Are you sure?", class: 'btn btn-sm btn-danger' %></td>
          <% end %>
          <td>
            <%= render 'books/favorite', book: @books %>
          </td>
          <td>コメント数：<%= @books.book_comments.count %></td>
        </tr>
      </table>

      <table>
        <% @books.book_comments.each do |book_comment|%>
          <tr>
           <td>
              <%= link_to user_path(book_comment.user.id) do %>
                <% if book_comment.user.profile_image.attached? %>
                  <%= image_tag book_comment.user.profile_image, size: "40x40" %>
                <% else %>
                  <%= image_tag 'no_image', size: "40x40" %>
                <% end %>
                <br>
            		<%= book_comment.user.name %>
              <% end %>
          	</td>
          	<td>
          		<%= book_comment.comment %>
          	</td>

          	<td>
          		<% if book_comment.user_id == current_user.id %>
          		<%= link_to "Destroy", book_book_comment_path(@books,book_comment.id), method: :delete, class: "btn-sm btn-danger" %>
          		<br>
          		<% end %>
          	</td>
          </tr>
        <% end %>
      </table>


      <div class="post-comment">
				<%= form_with model: @book_comment, url: book_book_comments_path(@books.id), method: :post, value: "" do |f| %>
				<%= f.text_area :comment, size: "80x10" %><br>
				<%= f.submit "送信" %>
				<% end %>
			</div>
    </div>
  </div>
</div>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="px-3 mx-auto">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class:'btn btn-info btn-sm btn-block mb-3 sign_in' %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class:'btn btn-success btn-sm btn-block sign_up' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    		<div class="container">
      		<a class="navbar-brand" href="/"><span>Bookers</span></a>
      		<div class="collapse navbar-collapse">
				  	<ul class="navbar-nav ml-auto">
				        <% if user_signed_in? %>
				          <li>
				          	<%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
				          		<i class="fas fa-home"></i> Home
                		<% end %>
				          </li>
				          <li>
				          	<%= link_to users_path, class:"nav-link text-light" do %>
				          		<i class="fas fa-users"></i> Users
                		<% end %>
				          </li>
				          <li>
				          	<%= link_to books_path, class:"nav-link text-light" do %>
				          		<i class="fas fa-book-open"></i> Books
                		<% end %>
				          </li>
				          <li>
				          	<%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light"  do %>
				          		<i class="fas fa-sign-out-alt"></i> logout
                		<% end %>
				          </li>
				        <% else %>
				          <li>
                    <%= link_to root_path, class: "nav-link text-light" do %>
                      <i class="fas fa-home"></i> Home
                    <% end %>
                  </li>
				          <li>
							      <%= link_to home_about_path, class:"nav-link text-light" do %>
				          		<i class="fas fa-link"></i> About
                		<% end %>
				          </li>
				          <li>
							      <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
				          		<i class="fas fa-user-plus"></i> sign up
                		<% end %>
				          </li>
				          <li>
							      <%= link_to new_user_session_path, class:"nav-link text-light" do %>
				          		<i class="fas fa-sign-in-alt"></i> login
                		<% end %>
				          </li>
				        <% end %>
				      </ul>
      		</div>
    		</div>
    	</nav>
    </header>
    <% if flash[:notice] %>
	    <p style="color: green">
	      <%= flash[:notice] %>
	    </p>
		<% end %>
		<main>
    	<%= yield %>
		</main>
    <footer>
    	<div class="container mt-5">
    		<div class="row">
    			<diV class="mx-auto">
    				<p>CopyRight Infratop.inc</p>
    			</diV>
    		</div>
    	</div>
    </footer>
  </body>
</html>

app/views/users/_user.html.erb
<h2>User info</h2>
<table class='table'>
  <tr>
    <% if user.profile_image.attached? %>
      <%= image_tag user.profile_image, size: "63x63" %>
    <% else %>
      <%= image_tag 'no_image', size: "63x63" %>
    <% end %>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
</table>
<div class='row'>
    <%= link_to edit_user_path(user.id),  class: 'btn btn-outline-secondary btn-block' do %>
  		<i class="fas fa-user-cog"></i>
  	<% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'books/error', model: @user %>
      <h2>User info</h2>
      <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :image %><br>
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>

        <div class="form-group">
          <%= f.label :introduction %><br>
          <%= f.text_area :introduction, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Update User', class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'user', user: @user %>

      <%= render 'books/book', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <% if user.profile_image.attached? %>
                <td><%= image_tag user.profile_image, size: "40x40" %></td>
              <% else %>
                <td><%= image_tag 'no_image', size: "40x40" %></td>
              <% end %>
              <td><%= user.name %></td>
              <td><%= link_to "Show" , user_path(user.id)%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'user', user: @user %>

      <%= render 'books/book', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <% if book.user.profile_image.attached? %>
                    <%= image_tag book.user.profile_image, size: "40x40" %>
                  <% else %>
                    <%= image_tag 'no_image', size: "40x40" %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <%= render 'books/favorite', book: book %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>